[package]
name = "n-sql"
version = "0.1.0"
authors = ["YISH <mokeyish@hotmail.com>"]
build = "build.rs" # LALRPOP preprocessing
license = "Apache-2.0/MIT"

[dependencies]
lalrpop-util = "0.16.3"
regex = "1.1.0"
codespan = "0.2"
codespan-reporting = "0.2"

[build-dependencies]
lalrpop = "0.16.3"